# -*- coding: utf-8 -*-
"""codigo_de_barras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhBn04MARiej8Feu70Pv9Cz4Dvqix3rO
"""

# TRABALHO 2 - DETECÇÃO DED CODIGO DE BARRAS
# MARIA EDUARDA SOARES

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Carrega a imagem
imagem_original = cv2.imread('barcode2.jpg')
# imagem na escala de cinza
imagem_cinza = cv2.cvtColor(imagem_original, cv2.COLOR_BGR2GRAY)

# 1. Filtrar linhas verticais
bordas = cv2.Canny(imagem_cinza, 50, 150, apertureSize=3)
linhas = cv2.HoughLinesP(bordas, 1, np.pi/180, threshold=80, minLineLength=30, maxLineGap=10)
mascara_linhas = np.zeros(imagem_cinza.shape, dtype=np.uint8)

if linhas is not None:
    for linha in linhas:
        x1, y1, x2, y2 = linha[0]
        if abs(x1 - x2) < 10:
            cv2.line(mascara_linhas, (x1, y1), (x2, y2), (255, 255, 255), 2)

# 2. Binalizar imagem
imagem_binarizada = mascara_linhas

# 3. Dilatação
kernel_dilatacao = cv2.getStructuringElement(cv2.MORPH_RECT, (35, 1))
imagem_dilatada = cv2.dilate(imagem_binarizada, kernel_dilatacao, iterations=1)

# 4. Erosão
kernel_erosao = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
imagem_erodida = cv2.erode(imagem_dilatada, kernel_erosao, iterations=2)

# 5. Caixa - controno codigo de barras
contornos, _ = cv2.findContours(imagem_erodida, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
imagem_resultado_final = cv2.cvtColor(imagem_original, cv2.COLOR_BGR2RGB)

if contornos:
    maior_contorno = max(contornos, key=cv2.contourArea)
    x, y, w, h = cv2.boundingRect(maior_contorno)

    padding_horizontal = 35
    padding_vertical = 5

    deslocamento_horizontal = 35

    x = x - padding_horizontal - deslocamento_horizontal # Subtrai o deslocamento aqui
    y = y - padding_vertical
    w = w + (padding_horizontal * 2)
    h = h + (padding_vertical * 2)

    # caixa nao ultrapassa imagem
    x = max(0, x)
    y = max(0, y)
    if (x + w) > imagem_resultado_final.shape[1]:
        w = imagem_resultado_final.shape[1] - x
    if (y + h) > imagem_resultado_final.shape[0]:
        h = imagem_resultado_final.shape[0] - y

    # desenha retangulo
    cv2.rectangle(imagem_resultado_final, (x, y), (x + w, y + h), (0, 255, 0), 3)

# Resultados
plt.figure(figsize=(15, 10))
plt.suptitle('Processo de Detecção de Código de Barras ', fontsize=16)

plt.subplot(2, 3, 1)
plt.imshow(cv2.cvtColor(imagem_original, cv2.COLOR_BGR2RGB))
plt.title('1. Imagem Original')
plt.axis('off')

plt.subplot(2, 3, 2)
plt.imshow(imagem_binarizada, cmap='gray')
plt.title('2. Linhas Verticais')
plt.axis('off')

plt.subplot(2, 3, 3)
plt.imshow(imagem_dilatada, cmap='gray')
plt.title('3. Após Dilatação')
plt.axis('off')

plt.subplot(2, 3, 4)
plt.imshow(imagem_erodida, cmap='gray')
plt.title('4. Após Erosão (Menos Agressiva)')
plt.axis('off')

plt.subplot(2, 3, 5)
plt.imshow(imagem_resultado_final)
plt.title('5. Resultado Final')
plt.axis('off')

plt.subplot(2, 3, 6).axis('off')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()